# Only expose the connected OMEN audio output.
[General]
auto-profiles = yes

[Mapping hdmi-stereo-extra4]
description = Digital Stereo (HDMI 5)
device-strings = hdmi:%f,4
paths-output = hdmi-output-4
channel-map = left,right
priority = 7
direction = output
