# Preserve the PodMic microphone without exposing playback ports.
[General]
auto-profiles = yes

[Mapping mono-fallback]
device-strings = hw:%f
fallback = yes
channel-map = mono
paths-input = analog-input-front-mic analog-input-rear-mic analog-input-internal-mic analog-input-dock-mic analog-input analog-input-mic analog-input-linein analog-input-aux analog-input-video analog-input-tvtuner analog-input-fm analog-input-mic-line analog-input-headset-mic
priority = 1
direction = input
